# Generated by Django 4.1.3 on 2023-05-14 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('stripe_payment_intent', models.CharField(max_length=200)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('customer_email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.userprofile', verbose_name='Customer Email')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.package', verbose_name='Package')),
            ],
        ),
    ]
