# Generated by Django 4.1.3 on 2023-06-08 20:32

from django.db import migrations, models
import services.models.package
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=30, null=True)),
                ('description', tinymce.models.HTMLField()),
                ('bullet_briefs', models.TextField(blank=True, help_text="Add each bullet sepeare by two dashes '--'", null=True, validators=[services.models.package.validate_bullet_briefs])),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
