# Generated by Django 4.1.3 on 2023-05-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='bullet_briefs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
