# Generated by Django 4.1.3 on 2023-05-20 21:51

from django.db import migrations, models
import services.models.package


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_package_bullet_briefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='subtitle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='bullet_briefs',
            field=models.TextField(blank=True, help_text="Add each bullet sepeare by two dashes '--'", null=True, validators=[services.models.package.validate_bullet_briefs]),
        ),
    ]
