# Generated by Django 4.1.3 on 2023-06-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_conditions_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
