# Generated by Django 4.1.3 on 2023-06-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_terms_conditions_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_terms_accepted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
