# Generated by Django 4.1.3 on 2023-06-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termsandconditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name': 'Terms and Conditions', 'verbose_name_plural': 'Terms and Conditions'},
        ),
        migrations.AddField(
            model_name='terms',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
